version: "3.1"
services:
  mongo:
    image: mongo:5.0.2
    container_name: "headlines-mongodb"
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "./data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: headlines
      MONGO_INITDB_ROOT_PASSWORD: senildeah
